revised to accept named arguments and other optimizations

diff --git a/ee-backfiller b/ee-backfiller
--- a/ee-backfiller
+++ b/ee-backfiller
@@ -1,27 +1,70 @@
 #!/bin/bash
 
-node=$1
-sid=$2
-sourceids=$(echo $sid | sed "s/\//%2F/g")
-startdate="$3T00%3A00"
-enddate="$4T23%3A59"
-maxoutput=$5
-lat=$6
-long=$7
-solcast_api_token=$8
-token=$9
-secret=${10} 
-log_path="logs/ee-backfiller.log"
+while [ $# -gt 0 ] ; do
+    case "$1" in
+    --node*|-n*)
+      if [[ "$1" != *=* ]]; then shift; fi # Value is next arg if no `=`
+      node="${1#*=}"
+      ;;
+    --sourceid*|-i*)
+      if [[ "$1" != *=* ]]; then shift; fi
+      sid="${1#*=}"
+      ;;
+    --startdate*|-s*)
+      if [[ "$1" != *=* ]]; then shift; fi
+      startdate="${1#*=}"
+      ;;
+    --enddate*|-e*)
+      if [[ "$1" != *=* ]]; then shift; fi
+      enddate="${1#*=}"
+      ;;
+    --latitude*|-a*)
+      if [[ "$1" != *=* ]]; then shift; fi
+      lat="${1#*=}"
+      ;;
+    --longitude*|-o*)
+      if [[ "$1" != *=* ]]; then shift; fi
+      long="${1#*=}"
+      ;;
+    --api*|-p*)
+      if [[ "$1" != *=* ]]; then shift; fi
+      solcast_api_token="${1#*=}"
+      ;;
+    --token*|-k*)
+      if [[ "$1" != *=* ]]; then shift; fi
+      token="${1#*=}"
+      ;;
+    --secret*|-c*)
+      if [[ "$1" != *=* ]]; then shift; fi
+      secret="${1#*=}"
+      ;;
+    --help|-h)
+      printf "Usage: ee-backfiller --node|-n [NODE] --sourceid|-i [SOURCEID] --startdate|-s [STARTDATE] --enddate|-e [ENDDATE] --latitude|-a [LATITUDE] --longitude|-o [LONGITUDE] --api|-p [SOLCAST API TOKEN] --token|-k [SOLNET TOKEN] --secret|-c [SOLNET SECRET]" # Flag argument
+      exit 0
+      ;;
+    *)
+      >&2 printf "Error: The following arguments are required --node --sourceid --startdate --enddate --latitude --longitude --api --token --secret \n"
+      exit 1
+      ;;
+  esac
+  shift
+done
 
-if [ "$#" -ne 10 ]; then
+if [[ -z "$node" || -z "$sid" || -z "$startdate" || -z "$enddate" || -z "$lat" || -z "$long" || -z "$solcast_api_token" || -z "$token" || -z "$secret" ]] ; then
 
-	echo "$(date +'%Y-%m-%d %H:%M:%S') Incorrect Number of Parameters. Usage: ee-backfiller [ node ] [ sourceids ] [ startdate ] [ enddate ] [ maxoutput ] [ lat ] [ long ] [ solcast_token ] [ solne_token ] [ solnet_secret ]" 2>&1 | tee -a $log_path
+        printf "Error: The following arguments are required --node --sourceid --startdate --enddate --latitude --longitude --api --token --secret \n" 2>&1 | tee -a $log_path
 
 else
+	echo "$(date +'%Y-%m-%d %H:%M:%S') Executed: /bin/bash ee-backfiller --node $node --sourceids $sid --startdate $startdate --enddate $enddate --latitude $lat --longitude $long --api $solcast_api_token --token $token --secret $secret" 2>&1 | tee -a $log_path
 
+	sourceids=$(echo $sid | sed "s/\//%2F/g")
+	startdate="${startdate}T00%3A00"
+	enddate="${enddate}T23%3A59"
+	log_path="logs/ee-backfiller.log"
+	maxoutput=1000000
 	echo "$(date +'%Y-%m-%d %H:%M:%S') *********** PROCESS 1 *************" 2>&1 | tee -a $log_path
 	echo "$(date +'%Y-%m-%d %H:%M:%S') Identifying gaps with aggregation in Days" 2>&1 | tee -a $log_path
-	echo "$(date +'%Y-%m-%d %H:%M:%S') Executing: python3 solnet_query.py $node $sourceids $startdate $enddate Day $maxoutput $token $secret" 2>&1 | tee -a $log_path
+	echo "$(date +'%Y-%m-%d %H:%M:%S') Executing: python3 solnet_query.py --node $node --sourceids $sourceids --startdate $startdate --enddate $enddate --aggregate Day --maxoutput $maxoutput --token $token --secret $secret" 2>&1 | tee -a $log_path
 	
 	first_row_days=0
 	gap_in_days=0
@@ -79,7 +122,7 @@ else
 		
 	echo "$(date +'%Y-%m-%d %H:%M:%S') ***********PROCESS 2*************" 2>&1 | tee -a $log_path
 	echo "$(date +'%Y-%m-%d %H:%M:%S') Identifying gaps in datum with aggregation in Hours $starthour and $endhour" 2>&1 | tee -a $log_path
-	echo "$(date +'%Y-%m-%d %H:%M:%S') Executing : python3 solnet_query.py $node $sourceids $starthour $endhour Hour $maxoutput $token $secret" 2>&1 | tee -a $log_path
+	echo "$(date +'%Y-%m-%d %H:%M:%S') Executing : python3 solnet_query.py --node $node --sourceids $sourceids --startdate $starthour --enddate $endhour --aggregate Hour --maxoutput $maxoutput --token $token --secret $secret" 2>&1 | tee -a $log_path
 
 	first_row_hours=0
 	gap_in_hours=0
@@ -164,7 +207,7 @@ else
 	
 	echo "$(date +'%Y-%m-%d %H:%M:%S') ***********PROCESS 3*************" 2>&1 | tee -a $log_path
 	echo "$(date +'%Y-%m-%d %H:%M:%S') Identifying gaps in datum with aggregation in Minutes bettwen $startdate and $enddate" 2>&1 | tee -a $log_path
-	echo "$(date +'%Y-%m-%d %H:%M:%S') Executing : python3 solnet_query.py $node $sourceids $startdate $enddate None $maxoutput $token $secret" 2>&1 | tee -a $log_path
+	echo "$(date +'%Y-%m-%d %H:%M:%S') Executing : python3 solnet_query.py --node $node --sourceids $sourceids --startdate $startdate --enddate $enddate --aggregate None --maxoutput $maxoutput --token $token --secret $secret" 2>&1 | tee -a $log_path
 	
 	first_row_minutes=0
 	gap_in_minutes=0
@@ -187,7 +230,6 @@ else
 			minute_difference=$((datetime_epoch - prevdatetime_epoch))
 			#echo "$datetime $minute_difference"
 			if [ $minute_difference -gt 600 ] ; then
-				#if [ $minute_difference -gt 1800 ] ; then
 					next_possible_gap_line_number=$(cat -n $minute_data_path | grep "$createdUTCDate" | awk '{print $1 }')
 					start_gap_line_number=$((next_possible_gap_line_number-1))
                                 	wattHours=$(awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' $minute_data_path | awk -F "," '{print $(NF-2)}' )
@@ -207,11 +249,6 @@ else
 					end_gap_localDate=$( awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' $minute_data_path | cut -d "," -f 4 )	
 					end_gap_localTime=$( awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' $minute_data_path | cut -d "," -f 5 )	
 					end_gap_watthours=$( awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' $minute_data_path | cut -d "," -f 23 )
-					#start_gap_localdatetime="$start_gap_localDate $start_gap_localTime"
-					#end_gap_localdatime="$end_gap_localDate $end_gap_localTime" 
-					#localDate=$(awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' $minute_data_path | cut -d "," -f 2 )
-                                	#localTime=$(awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' $minute_data_path | cut -d "," -f 3 )
-					
                                 	datetime=$(echo $createdUTCDate | sed "s/Z//g")
                         		echo "$(date +'%Y-%m-%d %H:%M:%S') Gap in UTC Found between $start_gap_created and $end_gap_created" 2>&1 | tee -a $log_path
                         		echo "$(date +'%Y-%m-%d %H:%M:%S') Gap in Local Found between $start_gap_localDate $start_gap_localTime:$start_gap_created_halfsec and $end_gap_localDate $end_gap_localTime:$end_gap_created_halfsec" 2>&1 | tee -a $log_path
@@ -222,9 +259,6 @@ else
  	                                end_gap_localdatetime="$end_gap_localDate $end_gap_localTime:$end_gap_created_halfsec"
 					gap_in_minutes=1
                         		break
-				#else
-				#	:
-				#fi
 			else
 				prevdatetime_epoch=$datetime_epoch
 			fi
diff --git a/ee-bad-data-deleter b/ee-bad-data-deleter
--- a/ee-bad-data-deleter
+++ b/ee-bad-data-deleter
@@ -1,21 +1,57 @@
 #!/bin/bash
 
-node=$1
-sourceids=$(echo $2 | sed "s/\//%2F/g")
-month=$3
-year=$4
-maxoutput=$5
-token=$6
-secret=$7 
+while [ $# -gt 0 ] ; do
+    case "$1" in
+    --node*|-n*)
+      if [[ "$1" != *=* ]]; then shift; fi # Value is next arg if no `=`
+      node="${1#*=}"
+      ;;
+    --sourceid*|-i*)
+      if [[ "$1" != *=* ]]; then shift; fi
+      sid="${1#*=}"
+      ;;
+    --month*|-m*)
+      if [[ "$1" != *=* ]]; then shift; fi
+      month="${1#*=}"
+      ;;
+    --year*|-y*)
+      if [[ "$1" != *=* ]]; then shift; fi
+      year="${1#*=}"
+      ;;
+    --token*|-k*)
+      if [[ "$1" != *=* ]]; then shift; fi
+      token="${1#*=}"
+      ;;
+    --secret*|-c*)
+      if [[ "$1" != *=* ]]; then shift; fi
+      secret="${1#*=}"
+      ;;
+    --help|-h)
+      printf "Usage: ee-bad-data-deleter --node|-n [NODE] --sourceid|-i [SOURCEID] --month|-m [MONTH] --year|-y [YEAR] --token|-k [SOLNET TOKEN] --secret|-c [SOLNET SECRET]\n" # Flag argument
+      exit 0
+      ;;
+    *)
+      >&2 printf "Error: The following arguments are required --node --sourceid --month --year --token --secret \n"
+      exit 1
+      ;;
+  esac
+  shift
+done
 
-rm -rf data/${node}_${sourceids}_${month}_${year}_scan_for_bad_data
-mkdir data/${node}_${sourceids}_${month}_${year}_scan_for_bad_data
->data/${node}_${sourceids}_${month}_${year}_scan_for_bad_data/${node}_${sourceids}_${month}_${year}_bad_data_results.csv
-if [ "$#" -ne 7 ]; then
+if [[ -z "$node" || -z "$sid" || -z "$month" || -z "$year" || -z "$token" || -z "$secret" ]] ; then
 
-        echo "$(date +'%Y-%m-%d %H:%M:%S') Incorrect Number of Parameters. Usage: ee-bad-data-deleter [node] [sourceids] [month] [year] [maxoutput] [token] [secret]" 2>&1 | tee -a logs/ee-bad-data-deleter.log
+        echo "$(date +'%Y-%m-%d %H:%M:%S') Error: The following arguments are required --node --sourceid --month --year --token --secret" 2>&1 | tee -a logs/ee-bad-data-deleter.log
 
 else
+	echo "$(date +'%Y-%m-%d %H:%M:%S') Executed: /bin/bash ee-bad-data-deleter --node $node --sourceids $sid --month $month --year $year --token $token --secret $secret" 2>&1 | tee -a $log_path
+
+
+	sourceids=$(echo $sid | sed "s/\//%2F/g")
+	maxoutput=1000000
+
+	rm -rf data/${node}_${sourceids}_${month}_${year}_scan_for_bad_data
+	mkdir data/${node}_${sourceids}_${month}_${year}_scan_for_bad_data
+	>data/${node}_${sourceids}_${month}_${year}_scan_for_bad_data/${node}_${sourceids}_${month}_${year}_bad_data_results.csv
 
 
 	startdate="$year-$month-01"
diff --git a/pyr-filler b/pyr-filler
--- a/pyr-filler
+++ b/pyr-filler
@@ -22,10 +22,6 @@ while [ $# -gt 0 ] ; do
       if [[ "$1" != *=* ]]; then shift; fi
       enddatetime="${1#*=}"
       ;;
-    --maxoutput*|-m*)
-      if [[ "$1" != *=* ]]; then shift; fi
-      maxoutput="${1#*=}"
-      ;;
     --latitude*|-a*)
       if [[ "$1" != *=* ]]; then shift; fi
       lat="${1#*=}"
@@ -47,25 +43,28 @@ while [ $# -gt 0 ] ; do
       secret="${1#*=}"
       ;;
     --help|-h)
-      printf "Usage: pyr-gapfiller [--help|-h] --node|-n [NODE] --sourceid|-i [SOURCE ID] --timezone|-z [TIMEZONE] --startdatetime|-s [START DATETIME] --enddatetime|-e [END DATETIME] --maxoutput|-m [MAX OUTPUT] --latitude|-a [LATITUDE] --longitude|-o [LONGITUDE] --api|-p [SOLCAST API TOKEN] --token|-k [SOLNET TOKEN] --secret|-c [SOLNET SECRET]" # Flag argument
+      printf "Usage: pyr-filler [--help|-h] --node|-n [NODE] --sourceid|-i [SOURCE ID] --timezone|-z [TIMEZONE] --startdatetime|-s [START DATETIME] --enddatetime|-e [END DATETIME] --latitude|-a [LATITUDE] --longitude|-o [LONGITUDE] --api|-p [SOLCAST API TOKEN] --token|-k [SOLNET TOKEN] --secret|-c [SOLNET SECRET]" # Flag argument
       exit 0
       ;;
     *)
-      >&2 printf "Error: The following arguments are required --node --sourceid --timezone --startdatetime --enddatetime --maxoutput --latitude --longitude --api --token --secret \n"
+      >&2 printf "Error: The following arguments are required --node --sourceid --timezone --startdatetime --enddatetime --latitude --longitude --api --token --secret \n"
       exit 1
       ;;
   esac
   shift
 done
 
-if [[ -z "$node" || -z "$sid" || -z "$timezone" || -z "$startdatetime" || -z "$enddatetime" || -z "$maxoutput" || -z "$lat" || -z "$long" || -z "$solcast_api_token" || -z "$token" || -z "$secret" ]] ; then
+if [[ -z "$node" || -z "$sid" || -z "$timezone" || -z "$startdatetime" || -z "$enddatetime" || -z "$lat" || -z "$long" || -z "$solcast_api_token" || -z "$token" || -z "$secret" ]] ; then
 
-	printf "Error: The following arguments are required --node --sourceids --startdate --enddate --maxoutput --latitude --longitude --api --token --secret \n"
+	printf "Error: The following arguments are required --node --sourceid --startdate --enddate --latitude --longitude --api --token --secret \n" 2>&1 | tee -a $log_path
 
 else
+	echo "$(date +'%Y-%m-%d %H:%M:%S') Executed: /bin/bash pyr-filler --node $node --sourceid $sid --timezone $timezone --localstartdate \"$localstartdate\" --enddate \"$localenddate\" --latitude $lat --longitude $long --api $solcast_api_token --token $token --secret $secret" 2>&1 | tee -a $log_path
+
 	sourceids=$(echo $sid | sed "s/\//%2F/g")
 	log_path="logs/pyr-filler.log"
-	
+	maxoutput=1000000
+
 	# Check timezone format if its valid
 	
 	check_timezone=$(awk '/^Z/ { print $2 }; /^L/ { print $timezone }' /usr/share/zoneinfo/tzdata.zi | grep -w $timezone)
@@ -92,7 +91,6 @@ else
 	startdate=$(echo $utcstartdate | sed 's/ /T/g;s/:/%3A/g')
 	enddate=$(echo $utcenddate | sed 's/ /T/g;s/:/%3A/g')
 
-	echo "$(date +'%Y-%m-%d %H:%M:%S') Executed: /bin/bash pyr-filler --node $node --sourceids $sourceids --timezone $timezone --localstartdate \"$localstartdate\" --enddate \"$localenddate\" --maxoutput $maxoutput --latitude $lat --longitude $long --api $solcast_api_token --token $token --secret $secret" 2>&1 | tee -a $log_path
 	echo "$(date +'%Y-%m-%d %H:%M:%S') Local : $localstartdate" 2>&1 | tee -a $log_path
 	echo "$(date +'%Y-%m-%d %H:%M:%S') UTC   : $utcstartdate" 2>&1 | tee -a $log_path
 	echo "$(date +'%Y-%m-%d %H:%M:%S') UTC Formatted : $startdate" 2>&1 | tee -a $log_path
diff --git a/pyr-gapfiller b/pyr-gapfiller
--- a/pyr-gapfiller
+++ b/pyr-gapfiller
@@ -18,10 +18,6 @@ while [ $# -gt 0 ] ; do
       if [[ "$1" != *=* ]]; then shift; fi
       enddate="${1#*=}"
       ;;
-    --maxoutput*|-m*)
-      if [[ "$1" != *=* ]]; then shift; fi
-      maxoutput="${1#*=}"
-      ;;
     --latitude*|-a*)
       if [[ "$1" != *=* ]]; then shift; fi
       lat="${1#*=}"
@@ -43,29 +39,30 @@ while [ $# -gt 0 ] ; do
       secret="${1#*=}"
       ;;
     --help|-h)
-      printf "Usage: pyr-gapfiller [--help|-h] --node|-n [NODE] --sourceid|-i [SOURCE IDS] --startdate|-s [START DATE] --enddate|-e [END DATE] --maxoutput|-m [MAX OUTPUT] --latitude|-a [LATITUDE] --longitude|-o [LONGITUDE] --api|-p [SOLCAST API TOKEN] --token|-k [SOLNET TOKEN] --secret|-c [SOLNET SECRET]" # Flag argument
+      printf "Usage: pyr-gapfiller [--help|-h] --node|-n [NODE] --sourceid|-i [SOURCE IDS] --startdate|-s [START DATE] --enddate|-e [END DATE] --latitude|-a [LATITUDE] --longitude|-o [LONGITUDE] --api|-p [SOLCAST API TOKEN] --token|-k [SOLNET TOKEN] --secret|-c [SOLNET SECRET]" # Flag argument
       exit 0
       ;;
     *)
-      >&2 printf "Error: The following arguments are required --node --sourceid --startdate --enddate --maxoutput --latitude --longitude --api --token --secret \n"
+      >&2 printf "Error: The following arguments are required --node --sourceid --startdate --enddate --latitude --longitude --api --token --secret \n"
       exit 1
       ;;
   esac
   shift
 done
 
-if [[ -z "$node" || -z "$sid" || -z "$startdate" || -z "$enddate" || -z "$maxoutput" || -z "$lat" || -z "$long" || -z "$solcast_api_token" || -z "$token" || -z "$secret" ]] ; then
+if [[ -z "$node" || -z "$sid" || -z "$startdate" || -z "$enddate" || -z "$lat" || -z "$long" || -z "$solcast_api_token" || -z "$token" || -z "$secret" ]] ; then
         
-	printf "Error: The following arguments are required --node --sourceids --startdate --enddate --maxoutput --latitude --longitude --api --token --secret \n"
+	printf "Error: The following arguments are required --node --sourceid --startdate --enddate --latitude --longitude --api --token --secret \n"
 
 else
+
+	echo "$(date +'%Y-%m-%d %H:%M:%S') Executed: /bin/bash pyr-gapfiller --node $node --sourceid $sid --startdate $startdate --enddate $enddate --latitude $lat --longitude $long --api $solcast_api_token --token $token --secret $secret" 2>&1 | tee -a $log_path
 
 	sourceids=$(echo $sid | sed "s/\//%2F/g")
 	startdate="${startdate}T00%3A00"
 	enddate="${enddate}T23%3A59"
 	log_path="logs/pyr-gapfiller.log"
-        
-	echo "$(date +'%Y-%m-%d %H:%M:%S') Executed: /bin/bash pyr-gapfiller --node $node --sourceids $sourceids --startdate $startdate --enddate $enddate --maxoutput $maxoutput --latitude $lat --longitude $long --api $solcast_api_token --token $token --secret $secret" 2>&1 | tee -a $log_path
+ 	maxouput=1000000       
 
 	# Process 1 extracts Solnet PYR data in day aggregates
         # Sample output file data/379_%2FVI%2FSU%2FB1%2FPYR%2F1_2020-01-31T00%3A00_2020-02-01T23%3A59_datum_days
