optimized and improved structure

diff --git a/pyr-gapfiller b/pyr-gapfiller
--- a/pyr-gapfiller
+++ b/pyr-gapfiller
@@ -1,109 +1,121 @@
 #!/bin/bash
 
 while [ $# -gt 0 ] ; do
-    case "$1" in
+  case "$1" in
     --node*|-n*)
-      if [[ "$1" != *=* ]]; then shift; fi # Value is next arg if no `=`
-      node="${1#*=}"
-      ;;
+	    if [[ "$1" != *=* ]]; then shift; fi 
+	    node="${1#*=}"
+	    ;;
     --sourceid*|-i*)
-      if [[ "$1" != *=* ]]; then shift; fi
-      sid="${1#*=}"
-      ;;
+	    if [[ "$1" != *=* ]]; then shift; fi
+	    sid="${1#*=}"
+	    ;;
     --startdatetime*|-s*)
-      if [[ "$1" != *=* ]]; then shift; fi
-      startdatetime="${1#*=}"
-      ;;
+	    if [[ "$1" != *=* ]]; then shift; fi
+	    startdatetime="${1#*=}"
+	    ;;
     --enddatetime*|-e*)
-      if [[ "$1" != *=* ]]; then shift; fi
-      enddatetime="${1#*=}"
-      ;;
+	    if [[ "$1" != *=* ]]; then shift; fi
+	    enddatetime="${1#*=}"
+	    ;;
     --latitude*|-a*)
-      if [[ "$1" != *=* ]]; then shift; fi
-      lat="${1#*=}"
-      ;;
+	    if [[ "$1" != *=* ]]; then shift; fi
+	    lat="${1#*=}"
+	    ;;
     --longitude*|-o*)
-      if [[ "$1" != *=* ]]; then shift; fi
-      long="${1#*=}"
-      ;;
+	    if [[ "$1" != *=* ]]; then shift; fi
+	    long="${1#*=}"
+	    ;;
     --api*|-p*)
-      if [[ "$1" != *=* ]]; then shift; fi
-      solcast_api_token="${1#*=}"
-      ;;
+	    if [[ "$1" != *=* ]]; then shift; fi
+	    solcast_api_token="${1#*=}"
+	    ;;
     --token*|-k*)
-      if [[ "$1" != *=* ]]; then shift; fi
-      token="${1#*=}"
-      ;;
+	    if [[ "$1" != *=* ]]; then shift; fi
+	    token="${1#*=}"
+	    ;;
     --secret*|-c*)
-      if [[ "$1" != *=* ]]; then shift; fi
-      secret="${1#*=}"
-      ;;
+	    if [[ "$1" != *=* ]]; then shift; fi
+	    secret="${1#*=}"
+	    ;;
     --help|-h)
-      printf "Usage: pyr-gapfiller [--help|-h] --node|-n [NODE] --sourceid|-i [SOURCE IDS] --startdate|-s [START DATETIME in \"YYYY-MM-DD HH:MM\"] --enddate|-e [END DATETIME in \"YYYY-MM-DD HH:MM\"] --latitude|-a [LATITUDE] --longitude|-o [LONGITUDE] --api|-p [SOLCAST API TOKEN] --token|-k [SOLNET TOKEN] --secret|-c [SOLNET SECRET]" # Flag argument
-      exit 0
-      ;;
+	    echo -n "Usage: pyr-gapfiller [--help|-h] --node|-n [NODE] --sourceid|-i [SOURCE IDS] " 
+	    echo -n "--startdate|-s [START DATETIME in \"YYYY-MM-DD HH:MM\"] --enddate|-e [END DATETIME in \"YYYY-MM-DD HH:MM\"] " 
+	    echo -n "--latitude|-a [LATITUDE] --longitude|-o [LONGITUDE] --api|-p [SOLCAST API TOKEN] --token|-k [SOLNET TOKEN] "
+	    echo    "--secret|-c [SOLNET SECRET]"
+	    exit 0
+	    ;;
     *)
-      >&2 printf "Error: The following arguments are required --node --sourceid --startdatetime --enddatetime --latitude --longitude --api --token --secret \n"
-      exit 1
-      ;;
+	    >&2 echo -n "Error: The following arguments are required --node --sourceid --startdatetime --enddatetime --latitude "
+	    echo "--longitude --api --token --secret"
+	    exit 1
+	    ;;
   esac
   shift
 done
 
-if [[ -z "$node" || -z "$sid" || -z "$startdatetime" || -z "$enddatetime" || -z "$lat" || -z "$long" || -z "$solcast_api_token" || -z "$token" || -z "$secret" ]] ; then
-        
-	printf "Error: The following arguments are required --node --sourceid --startdatetime --enddatetime --latitude --longitude --api --token --secret \n"
+if 	[[ -z "$node" || -z "$sid" || -z "$startdatetime" || -z "$enddatetime" || -z "$lat" || \
+	-z "$long" || -z "$solcast_api_token" || -z "$token" || -z "$secret" ]]
+then        
+	echo -n "Error: The following arguments are required --node --sourceid --startdatetime"
+        echo	"--enddatetime --latitude --longitude --api --token --secret"
 
 else
-    
-    # Formatted for file labels. Python scripts can parse these parameters its original format. 
-    sourceids=$(echo $sid | sed "s/\//%2F/g")
-    startdate=$(echo ${startdatetime} | sed "s/ /T/g;s/:/%3A/g")
-    enddate=$(echo ${enddatetime} | sed "s/ /T/g;s/:/%3A/g")
-    
-    # Constants
-    log_path="logs/pyr-gapfiller.log"
-    maxoutput=1000000
-
-    echo "$(date +'%Y-%m-%d %H:%M:%S') Testing parameters with python3 solnet_query.py --node=\"$node\" --sourceids=\"$sourceids\" --startdate=\"$startdate\" --enddate=\"$enddate\" --aggregate=\"Month\" --maxoutput=\"1000000\" --token=\"$token\" --secret=\"$secret\"" 2>&1 | tee -a $log_path
-    test_params=$(python3 solnet_query.py --node="$node" --sourceids="$sourceids" --startdate="$startdate" --enddate="$enddate" --aggregate="Month" --maxoutput="1000000" --token="$token" --secret="$secret")
-    echo "$(date +'%Y-%m-%d %H:%M:%S') $test_params" 2>&1 | tee -a $log_path
-
-    if [[ "$test_params" == *"Error"* ]] ; then
-                echo "$(date +'%Y-%m-%d %H:%M:%S') Usage: pyr-gapfiller [--help|-h] --node|-n [NODE] --sourceid|-i [SOURCE IDS] --startdate|-s [START DATETIME in \"YYYY-MM-DD HH:MM\"] --enddate|-e [END DATETIME in \"YYYY-MM-DD HH:MM\"] --latitude|-a [LATITUDE] --longitude|-o [LONGITUDE] --api|-p [SOLCAST API TOKEN] --token|-k [SOLNET TOKEN] --secret|-c [SOLNET SECRET]" 2>&1 | tee -a $log_path
-    else
-
-	echo "$(date +'%Y-%m-%d %H:%M:%S') Executed: /bin/bash pyr-gapfiller --node $node --sourceid $sid --startdatetime $startdatetime --enddatetime $enddatetime --latitude $lat --longitude $long --api $solcast_api_token --token $token --secret $secret" 2>&1 | tee -a $log_path
-
-	# Process 1 extracts Solnet PYR data in day aggregates
-        # Sample output file data/379_%2FVI%2FSU%2FB1%2FPYR%2F1_2020-01-31T00%3A00_2020-02-01T23%3A59_datum_days
-        # Sample contents of file
-        # created,localDate localTime nodeId sourceId irradiance_min irradiance_max irradiance irradianceHours
-        # 2020-01-31 04:00:00Z,2020-01-31,00:00,379,/VI/SU/B1/PYR/1,0,846,191.47222222222223,-133365.783
-        # 2020-02-01 04:00:00Z,2020-02-01,00:00,379,/VI/SU/B1/PYR/1,0,845,220.625,5292.3293
-
-	echo "$(date +'%Y-%m-%d %H:%M:%S') *********** PROCESS 1 *************" 2>&1 | tee -a $log_path
-	echo "$(date +'%Y-%m-%d %H:%M:%S') Identifying gaps with aggregation in Days" 2>&1 | tee -a $log_path
-	echo "$(date +'%Y-%m-%d %H:%M:%S') Executing: python3 solnet_query.py --node=\"$node\" --sourceids=\"$sourceids\" --startdate=\"$startdate\" --enddate=\"$enddate\" --aggregate=\"Day\" --maxoutput=\"$maxoutput\" --token=\"$token\" --secret=\"$secret\"" 2>&1 | tee -a $log_path
+	# Formatted for file labels. Python scripts can parse these parameters its original format. 
+	sourceids=$(echo $sid | sed "s/\//%2F/g")
+	startdate=$(echo ${startdatetime} | sed "s/ /T/g;s/:/%3A/g")
+	enddate=$(echo ${enddatetime} | sed "s/ /T/g;s/:/%3A/g")
+	# Constants
+	log_path="logs/pyr-gapfiller.log"
+	maxoutput=1000000
 	
-	# Initialization of variables       
-	first_row_days=0
-	gap_in_days=0
+	echo -n "$(date +'%Y-%m-%d %H:%M:%S') Testing parameters with python3 solnet_query.py "
+	echo -n "--node=\"$node\" --sourceids=\"$sourceids\" --startdate=\"$startdate\" --enddate=\"$enddate\" "
+        echo    "--aggregate=\"Month\" --maxoutput=\"1000000\" --token=\"$token\" --secret=\"$secret\"" 2>&1 | tee -a $log_path
+	test_params=$(python3 solnet_query.py --node="$node" --sourceids="$sourceids" --startdate="$startdate" \
+		--enddate="$enddate" --aggregate="Month" --maxoutput="1000000" --token="$token" --secret="$secret")
+	
+	echo "$(date +'%Y-%m-%d %H:%M:%S') $test_params" 2>&1 | tee -a $log_path
+	
+	if [[ "$test_params" == *"Error"* ]] ; then
+		echo -n "$(date +'%Y-%m-%d %H:%M:%S') Usage: pyr-gapfiller [--help|-h] --node|-n [NODE] --sourceid|-i "
+		echo -n "[SOURCE IDS] --startdate|-s [START DATETIME in \"YYYY-MM-DD HH:MM\"] --enddate|-e [END DATETIME in "
+		echo -n "\"YYYY-MM-DD HH:MM\"] --latitude|-a [LATITUDE] --longitude|-o [LONGITUDE] --api|-p [SOLCAST API TOKEN] "
+		echo 	"--token|-k [SOLNET TOKEN] --secret|-c [SOLNET SECRET]" 2>&1 | tee -a $log_path
+	else
+		echo -n "$(date +'%Y-%m-%d %H:%M:%S') Executed: /bin/bash pyr-gapfiller --node $node --sourceid $sid "
+		echo -n "--startdatetime $startdatetime --enddatetime $enddatetime --latitude $lat --longitude $long "
+		echo    "--api $solcast_api_token --token $token --secret $secret" 2>&1 | tee -a $log_path
+		
+		# Process 1 extracts Solnet PYR data in day aggregates
+		echo "$(date +'%Y-%m-%d %H:%M:%S') *********** PROCESS 1 *************" 2>&1 | tee -a $log_path
+		echo "$(date +'%Y-%m-%d %H:%M:%S') Identifying gaps with aggregation in Days" 2>&1 | tee -a $log_path
+		echo -n "$(date +'%Y-%m-%d %H:%M:%S') Executing: python3 solnet_query.py --node=\"$node\" --sourceids=\"$sourceids\" "
+	        echo -n "--startdate=\"$startdate\" --enddate=\"$enddate\" --aggregate=\"Day\" --maxoutput=\"$maxoutput\" " 
+		echo    "--token=\"$token\" --secret=\"$secret\"" 2>&1 | tee -a $log_path
+		
+		# Initialization of variables       
+		first_row_days=0
+		gap_in_days=0
 
-	# File path of the output file with PYR data in day aggregates
-	day_data_path="data/${node}_${sourceids}_${startdate}_${enddate}_datum_days"
-	# Python command to extract PYR data. Note the aggregate parameter is set to Day and dates are in UTC.
+		# File path of the output file with PYR data in day aggregates
+		day_data_path="data/${node}_${sourceids}_${startdate}_${enddate}_datum_days"
+		# Python command to extract PYR data. Note the aggregate parameter is set to Day and dates are in UTC.
+		
+		python3 solnet_query.py --node="$node" --sourceids="$sourceids" --startdate="$startdate" --enddate="$enddate" \
+			--aggregate="Day" --maxoutput="$maxoutput" --token="$token" --secret="$secret" > $day_data_path
+					
+		# Removes column header from output file, not needed for the next process
+		sed -i '1d' $day_data_path
+		sleep 1
+		total_lines=$(cat $day_data_path | wc -l)
 
-	python3 solnet_query.py --node="$node" --sourceids="$sourceids" --startdate="$startdate" --enddate="$enddate" --aggregate="Day" --maxoutput="$maxoutput" --token="$token" --secret="$secret" > $day_data_path
-	# Removes column header from output file, not needed for the next process
-	sed -i '1d' $day_data_path
-	sleep 1
-	total_lines=$(cat $day_data_path | wc -l)
-
-	# Iterate through the file with PYR data in day aggregates to identify gaps. It compares the local date with a future date that is one day ahead
-    	# If it doesn't match then the start of a possible gap is identified 	
-	while IFS=, read UTCDateTime localDate localTime nodeId sourceId irradiance_min irradiance_max irradiance irradianceHours
-	do
+		# Iterate through the file with PYR data in day aggregates to identify gaps.
+		# It compares the local date with a future date that is one day ahead
+    		# If it doesn't match then the start of a possible gap is identified 	
+		
+		while IFS=, read UTCDateTime localDate localTime nodeId sourceId irradiance_min irradiance_max irradiance irradianceHours
+		do
 		# Determines first row
 		if [[ $first_row_days == 0 ]] ; then
 			first_row_days=1
@@ -119,15 +131,20 @@ else
 				break
                          fi
 
-                         next_irradiance=$(awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' $day_data_path | cut -d "," -f 8 )
-                         next_irradianceHours=$(awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' $day_data_path | cut -d "," -f 9 )
+                         next_irradiance=$(awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' $day_data_path | \
+				 cut -d "," -f 8 )
+                         next_irradianceHours=$(awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' $day_data_path | \
+				 cut -d "," -f 9 )
 
-			# Compares next iteration of dates to the expected date which is a day ahead, if it matches then not a start gap date, else a possible start gap date 
-			if [[ "$localDate" != "$expected_next_localDate" ]] || [[ -z "$next_irradiance" ]] || [[ -z "$next_irradianceHours" ]]; then
+			# Compares next iteration of dates to the expected date which is a day ahead, if it matches then not a start 
+			# gap date, else a possible start gap date 
+			if [[ "$localDate" != "$expected_next_localDate" ]] || [[ -z "$next_irradiance" ]] || [[ -z "$next_irradianceHours" ]] 
+			then
+				# Next process show that once a possible start gap date is identified, its not yet definitive that the next 
+				# date iteration is the end gap date as it could be bad data where irradiance hours is zero or null
 				
-				# Next process show that once a possible start gap date is identified, its not yet definitive that the next date iteration is the end gap date as it could be bad data where irradiance hours is zero or null
-				
-				# Checks current iteration if the irradiance or irradiance hours have empty values, while this is true, it continues to iterate through the data 
+				# Checks current iteration if the irradiance or irradiance hours have empty values, while this is true, it 
+				# continues to iterate through the data 
 				# and increments the line number of the possible end gap until the datum is valid
 				
 				if [[ "$localDate" != "$expected_next_localDate" ]] ; then
@@ -141,13 +158,17 @@ else
 				while [[ -z "$next_irradiance" ]] || [[ -z "$next_irradianceHours" ]]
                                 do
                                         next_possible_gap_line_number=$((next_possible_gap_line_number+1))
-                                        next_irradiance=$(awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' $day_data_path | cut -d "," -f 8)
-                                        next_irradianceHours=$(awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' $day_data_path | cut -d "," -f 9)
+                                        next_irradiance=$(awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' \
+						$day_data_path | cut -d "," -f 8)
+                                        next_irradianceHours=$(awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' \
+						$day_data_path | cut -d "," -f 9)
                                 done
 
 				# Once the line number of the end gap is determined, then extract the utc and local dates from the line
-				start_gap_utc_date=$(awk -v num="$start_gap_line_number" '{if(NR==num) print $0}' $day_data_path | cut -d "," -f 1 )
-				end_gap_utc_date=$(awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' $day_data_path | cut -d "," -f 1 )
+				start_gap_utc_date=$(awk -v num="$start_gap_line_number" '{if(NR==num) print $0}' \
+					$day_data_path | cut -d "," -f 1 )
+				end_gap_utc_date=$(awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' \
+					$day_data_path | cut -d "," -f 1 )
 				
 				# Formats the dates to be used in the next process in determining the gap in data aggregated hourly
 
@@ -305,25 +326,20 @@ else
 				start_gap_utc_datetime=$(awk -v num="$start_gap_line_number" '{if(NR==num) print $0}' $minute_data_path | cut -d "," -f 1 )
 				end_gap_utc_datetime=$(awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' $minute_data_path | cut -d "," -f 1 )
 				
-				start_gap_utc_datetime_halfsec=$(echo $start_gap_utc_datetime | awk -F ':' '{print $NF}' | sed 's/Z//g')
-				end_gap_utc_datetime_halfsec=$(echo $end_gap_utc_datetime | awk -F ':' '{print $NF}' | sed 's/Z//g')	
+				start_gap_halfsec=$(echo $start_gap_utc_datetime | awk -F ':' '{print $NF}' | sed 's/Z//g')
+				end_gap_halfsec=$(echo $end_gap_utc_datetime | awk -F ':' '{print $NF}' | sed 's/Z//g')	
 
-				start_gap_localDate=$(awk -v num="$start_gap_line_number" '{if(NR==num) print $0}' $minute_data_path | cut -d "," -f 2 )
-				start_gap_localTime=$(awk -v num="$start_gap_line_number" '{if(NR==num) print $0}' $minute_data_path | cut -d "," -f 3 )
+				start_gap_localdatetime=$(awk -v num="$start_gap_line_number" '{if(NR==num) print $0}' $minute_data_path | cut -d "," -f 2,3 | sed "s/,/ /g;s/$/:${start_gap_halfsec}/g")
+                                end_gap_localdatetime=$(awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' $minute_data_path | cut -d "," -f 2,3 | sed "s/,/ /g;s/$/:${end_gap_halfsec}/g")
+
 				start_gap_irradiancehours=$(awk -v num="$start_gap_line_number" '{if(NR==num) print $0}' $minute_data_path | cut -d "," -f 7 )
-				
-				end_gap_localDate=$( awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' $minute_data_path | cut -d "," -f 2 )	
-				end_gap_localTime=$( awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' $minute_data_path | cut -d "," -f 3 )	
 				end_gap_irradiancehours=$( awk -v num="$next_possible_gap_line_number" '{if(NR==num) print $0}' $minute_data_path | cut -d "," -f 7 )
                         
-				datetime=$(echo $createdUTCDate | sed "s/Z//g")
                         	echo "$(date +'%Y-%m-%d %H:%M:%S') Gap in UTC Found between $start_gap_utc_datetime and $end_gap_utc_datetime" 2>&1 | tee -a $log_path
-                        	echo "$(date +'%Y-%m-%d %H:%M:%S') Gap in Local Found between $start_gap_localDate $start_gap_localTime:$start_gap_utc_datetime_halfsec and $end_gap_localDate $end_gap_localTime:$end_gap_utc_datetime_halfsec" 2>&1 | tee -a $log_path
+                        	echo "$(date +'%Y-%m-%d %H:%M:%S') Gap in Local Found between $start_gap_localdatetime and $end_gap_localdatetime" 2>&1 | tee -a $log_path
 					
 				start_gap=$start_gap_utc_datetime
 				end_gap=$end_gap_utc_datetime
-				start_gap_localdatetime="$start_gap_localDate $start_gap_localTime:$start_gap_utc_datetime_halfsec"
- 	                        end_gap_localdatetime="$end_gap_localDate $end_gap_localTime:$end_gap_utc_datetime_halfsec"
 				gap_in_minutes=1
                         	break
 			else
